# Uncomment the next line to define a global platform for your project
platform :ios, '12.4'

target 'MyPlaces' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

 pod 'RealmSwift', '~> 3.17.3'

end
